/**
 * Fixture types are authored to match the eventual Postgres shape, so wiring
 * later is a data-source swap and not a component refactor.
 *
 * Money is integer PAISA. Dates are ISO `yyyy-mm-dd`.
 */

export type ID = string;
export type ISODate = string;

export type Currency = "PKR" | "USD" | "GBP" | "EUR" | "AED";

export type InstitutionKind = "bank" | "wallet" | "utility" | "brand" | "gov";

export type Institution = {
  id: ID;
  name: string;
  short: string;
  kind: InstitutionKind;
  /** Brand colour, used for card art and the monogram fallback. */
  brand: string;
  /** On-brand foreground for text sitting on `brand`. */
  onBrand: string;
  /** `/logos/<slug>.webp` once sourced; monogram fallback until then. */
  logo?: string;
};

export type AccountKind =
  | "cash"
  | "bank"
  | "credit_card"
  | "wallet"
  | "loan"
  | "asset";

export type Account = {
  id: ID;
  name: string;
  kind: AccountKind;
  institutionId: ID | null;
  currency: Currency;
  balancePaisa: number;
  last4?: string;
  /** Islamic banking — changes which products are offered against it. */
  islamic?: boolean;
};

export type CategoryKind = "expense" | "income";

export type Category = {
  id: ID;
  parentId: ID | null;
  name: string;
  kind: CategoryKind;
  /** lucide icon name */
  icon: string;
  /** chart token 1-6 */
  tone: 1 | 2 | 3 | 4 | 5 | 6;
};

export type Merchant = {
  id: ID;
  name: string;
  categoryId: ID;
  institutionId?: ID;
  brand: string;
  logo?: string;
};

export type TransactionKind = "expense" | "income" | "transfer";

export type Transaction = {
  id: ID;
  date: ISODate;
  accountId: ID;
  merchantId: ID | null;
  categoryId: ID;
  /** Negative for money out, positive for money in. Always PKR paisa. */
  amountPaisa: number;
  kind: TransactionKind;
  note?: string;
  /** Set when the original was not PKR — the rate is snapshotted, not looked up. */
  originalCurrency?: Currency;
  originalAmount?: number;
  fxRate?: number;
  receiptId?: ID;
  /** Links the two halves of a transfer so net worth never double-counts. */
  transferPairId?: ID;
  /** Withholding deducted at source — feeds the FBR surface. */
  withholdingPaisa?: number;
};

export type Bill = {
  id: ID;
  name: string;
  merchantId: ID | null;
  categoryId: ID;
  accountId: ID;
  amountPaisa: number;
  dueDate: ISODate;
  status: "due" | "paid" | "overdue";
  /** Utility bills vary month to month; subscriptions do not. */
  fixed: boolean;
};

export type Budget = {
  id: ID;
  categoryId: ID;
  limitPaisa: number;
  spentPaisa: number;
};

export type CommitteeMember = {
  id: ID;
  name: string;
  /** 1-based month in the rotation this member collects. */
  payoutMonth: number;
  paidThisMonth: boolean;
  isSelf?: boolean;
};

export type Committee = {
  id: ID;
  name: string;
  monthlyPaisa: number;
  members: CommitteeMember[];
  startDate: ISODate;
  /** 1-based index of the cycle currently running. */
  currentMonth: number;
  accountId: ID;
};

export type PlanKind =
  | "nss_certificate"
  | "prize_bond"
  | "term_deposit"
  | "mutual_fund"
  | "equity"
  | "gold"
  | "property"
  | "committee"
  | "foreign";

export type InvestmentPlan = {
  id: ID;
  name: string;
  kind: PlanKind;
  provider: string;
  investedPaisa: number;
  currentPaisa: number;
  startDate: ISODate;
  maturityDate?: ISODate;
  /** Stated annual profit rate where the product has one (NSS, TDR). */
  ratePct?: number;
  /** Money-weighted return, computed — not stated. */
  xirr?: number;
  shariah: boolean;
  /** Gold is held in grams, displayed in tola. */
  grams?: number;
};

export type NetWorthPoint = {
  date: ISODate;
  assetsPaisa: number;
  liabilitiesPaisa: number;
};

export type Task = {
  id: ID;
  title: string;
  dueDate: ISODate;
  done: boolean;
  priority: "low" | "normal" | "high";
  /** Generated by the app rather than typed by the user. */
  auto?: boolean;
  linkedLabel?: string;
};

export type Dataset = {
  today: ISODate;
  institutions: Institution[];
  accounts: Account[];
  categories: Category[];
  merchants: Merchant[];
  transactions: Transaction[];
  bills: Bill[];
  budgets: Budget[];
  committees: Committee[];
  plans: InvestmentPlan[];
  netWorth: NetWorthPoint[];
  tasks: Task[];
};
